// The 10 sample restaurants, in one place: both `npm run db:seed` and the
// admin "Create Sample Data" button read this list. cuisines/tags are stored
// as JSON strings because SQLite has no array type — see prisma/schema.prisma.
// Values are VocabTerm slugs, seeded by the vocab_terms migration.
export const sampleRestaurants = [
  {
    name: 'The Light Bite Cafe',
    description: 'Fresh salads, smoothies, and light sandwiches. Perfect for a healthy lunch.',
    heaviness: 20,
    portionSize: 40,
    fineDining: 30,
    priceLevel: 2,
    avgPrepTime: 15,
    cuisines: JSON.stringify(['healthy', 'cafe']),
    neighborhood: 'qendra',
  },
  {
    name: 'Mama Rosa\'s Italian Kitchen',
    description: 'Authentic Italian pasta and pizza. Family-friendly atmosphere.',
    heaviness: 70,
    portionSize: 85,
    fineDining: 45,
    priceLevel: 2,
    avgPrepTime: 25,
    cuisines: JSON.stringify(['italian', 'pizza']),
    neighborhood: 'dardania',
  },
  {
    name: 'Le Château Fine Dining',
    description: 'Elegant French cuisine with impeccable service. Perfect for special occasions.',
    heaviness: 60,
    portionSize: 70,
    fineDining: 95,
    priceLevel: 4,
    avgPrepTime: 45,
    cuisines: JSON.stringify(['international']),
    neighborhood: 'velania',
  },
  {
    name: 'Spicy Dragon Szechuan',
    description: 'Authentic Szechuan cuisine with bold flavors and heat.',
    heaviness: 65,
    portionSize: 75,
    fineDining: 50,
    priceLevel: 2,
    avgPrepTime: 20,
    cuisines: JSON.stringify(['sushi-asian']),
    neighborhood: 'ulpiane',
  },
  {
    name: 'Burger Express',
    description: 'Quick-service burgers and fries. Fast and filling.',
    heaviness: 80,
    portionSize: 90,
    fineDining: 15,
    priceLevel: 1,
    avgPrepTime: 10,
    cuisines: JSON.stringify(['burgers', 'fast-food']),
    neighborhood: 'bregu-i-diellit',
  },
  {
    name: 'Sushi Zen',
    description: 'Fresh sushi and sashimi. Minimalist Japanese aesthetic.',
    heaviness: 35,
    portionSize: 50,
    fineDining: 70,
    priceLevel: 3,
    avgPrepTime: 30,
    cuisines: JSON.stringify(['sushi-asian']),
    neighborhood: 'pejton',
  },
  {
    name: 'Taco Fiesta',
    description: 'Vibrant Mexican street food. Casual and fun atmosphere.',
    heaviness: 55,
    portionSize: 70,
    fineDining: 25,
    priceLevel: 1,
    avgPrepTime: 12,
    cuisines: JSON.stringify(['mexican', 'fast-food']),
    neighborhood: 'arberia',
  },
  {
    name: 'The Steakhouse',
    description: 'Premium cuts of meat, classic sides, and extensive wine list.',
    heaviness: 90,
    portionSize: 95,
    fineDining: 80,
    priceLevel: 4,
    avgPrepTime: 40,
    cuisines: JSON.stringify(['steakhouse', 'burgers']),
    neighborhood: 'qendra',
  },
  {
    name: 'Green Garden Vegan',
    description: 'Plant-based cuisine with creative flavors. All organic ingredients.',
    heaviness: 40,
    portionSize: 60,
    fineDining: 55,
    priceLevel: 3,
    avgPrepTime: 20,
    cuisines: JSON.stringify(['vegan', 'healthy']),
    neighborhood: 'kalabria',
  },
  {
    name: 'Ramen House',
    description: 'Authentic Japanese ramen with rich broths and perfect noodles.',
    heaviness: 75,
    portionSize: 80,
    fineDining: 40,
    priceLevel: 2,
    avgPrepTime: 15,
    cuisines: JSON.stringify(['sushi-asian']),
    neighborhood: 'tophane',
  },
]
